name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.0.x', '1.2.x', '1.4.x', 'stable']
        include:
          - nim-version: '1.4.x'
            gc_orc: true
          - nim-version: 'stable'
            gc_orc: true

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
    - run: nimble test -d:release -y
    - run: nimble test -d:release -d:lto -y
    - run: nimble test --gc:orc -d:release -y
      if: ${{ matrix.gc_orc }}
    - run: nim cpp -d:release -r tests/all.nim
